const Hosteldata = {
  vijaynagar: [
    {
      name: 'Sunshine Hostel',
      address: '123 Vijay Nagar Rd',
      image: '/photos/download.jpg',
      rating: 4.5,
      price: 5000,
      gender: 'boys',
      features: ['WiFi', 'Laundry', 'AC', 'CCTV', 'Food'],
    },
    {
      name: 'Elite Girls PG',
      address: 'Vijay Nagar Square',
      image: '/photos/download2.jpg',
      rating: 4.8,
      price: 6000,
      gender: 'girls',
      features: ['WiFi', 'Laundry', 'AC', 'Food'],
    },
    {
      name: 'City Stay',
      address: '45 MG Road',
      image: '/photos/download1.jpg',
      rating: 4.2,
      price: 4500,
      gender: 'boys',
      features: ['WiFi', 'Laundry', 'Cleaning'],
    },
    {
      name: 'Green Nest',
      address: 'A-102 Vikas Nagar',
      image: '/photos/download3.jpg',
      rating: 4.6,
      price: 5200,
      gender: 'girls',
      features: ['WiFi', 'Laundry', 'AC', 'CCTV'],
    },
    {
      name: 'Skyline Residency',
      address: 'Vijaynagar Main Road',
      image: '/photos/download2.jpg',
      rating: 4.9,
      price: 7000,
      gender: 'boys',
      features: ['WiFi', 'Gym', 'AC', 'CCTV'],
    },
  ],
  palasia: [
    {
      name: 'Comfort Nest',
      address: 'Near Palasia Square',
      image: '/photos/download3.jpg',
      rating: 4.5,
      price: 5000,
      gender: 'girls',
      features: ['WiFi', 'Laundry', 'AC'],
    },
    {
      name: 'Palasia Residency',
      address: '101 AB Road',
      image: '/photos/download2.jpg',
      rating: 4.0,
      price: 5000,
      gender: 'boys',
      features: ['WiFi', 'Laundry', 'Cleaning'],
    },
    {
      name: 'Oasis Hostel',
      address: 'Palasia Extension',
      image: '/photos/download1.jpg',
      rating: 4.5,
      price: 5000,
      gender: 'boys',
      features: ['WiFi', 'Laundry', 'CCTV'],
    },
    {
      name: 'Zen PG',
      address: 'Old Palasia Rd',
      image: '/photos/download.jpg',
      rating: 4.7,
      price: 5500,
      gender: 'girls',
      features: ['WiFi', 'Laundry', 'AC', 'Food'],
    },
  ],
  bholaram: [
    {
      name: 'GreenView Hostel',
      address: 'Bholaram Campus',
      image: '/photos/download2.jpg',
      rating: 4.5,
      price: 5500,
      gender: 'boys',
      features: ['WiFi', 'Laundry', 'AC'],
    },
    {
      name: 'Peace PG',
      address: 'Sector A, Bholaram',
      image: '/photos/download1.jpg',
      rating: 4.8,
      price: 6000,
      gender: 'girls',
      features: ['WiFi', 'Laundry', 'AC'],
    },
    {
      name: 'Elite Girls PG',
      address: 'Sector B, Bholaram',
      image: '/photos/download2.jpg',
      rating: 4.2,
      price: 4000,
      gender: 'girls',
      features: ['WiFi', 'Laundry', 'AC'],
    },
    {
      name: 'Green Nest',
      address: 'A-102 Vikas Nagar',
      image: '/photos/download3.jpg',
      rating: 4.4,
      price: 3000,
      gender: 'boys',
      features: ['WiFi', 'Laundry', 'AC', 'CCTV'],
    },
  ],
  bhanwarkuwa: [
    {
      name: 'Metro Hostel',
      address: 'Opp RRC',
      image: '/photos/download3.jpg',
      rating: 4.4,
      price: 3000,
      gender: 'boys',
      features: ['WiFi', 'Laundry', 'AC', 'CCTV'],
    },
    {
      name: 'BK Rooms',
      address: 'Near DAVV',
      image: '/photos/download1.jpg',
      rating: 4.4,
      price: 3300,
      gender: 'boys',
      features: ['WiFi', 'Laundry', 'AC', 'CCTV'],
    },
    {
      name: 'Sky PG',
      address: 'RNT Marg, BK',
      image: '/photos/download2.jpg',
      rating: 4.4,
      price: 2000,
      gender: 'boys',
      features: ['WiFi', 'Laundry', 'AC', 'CCTV'],
    },
    {
      name: 'Elite Girls PG',
      address: 'RNT Marg, BK',
      image: '/photos/download2.jpg',
      rating: 5,
      price: 8000,
      gender: 'girls',
      features: ['WiFi', 'Laundry', 'AC', 'CCTV', 'Food'],
    },
    {
      name: 'Green Nest',
      address: 'A-102 Vikas Nagar',
      image: '/photos/download3.jpg',
      rating: 5,
      price: 8000,
      gender: 'girls',
      features: ['WiFi', 'Laundry', 'AC', 'CCTV', 'Food'],
    },
  ],
};

export default Hosteldata;
